# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2e464735abb322e41aecf1179ef85386458c0370175a1d3e88d5e1cd7ce6589872150a9b7c0520a45e193a8f8ada0f82145da2ab5731b010fa0626c02e85211

test:
  secret_key_base: 888e1e70a5656dad5620448afd17ce530256193242a310516d4b65ae8287b54c1844c09d8f8938ec6edd1bd66f8eb062bc4d5c674fe5aac0a77746f3eddbdf70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
